############################### 基本信息 ###############################
info:
  name: Material X
  docs: https://xaoxuu.com/wiki/material-x/
  cdn: # 把对应的那一行注释掉就使用本地的文件
    css:
      # style: https://cdn.jsdelivr.net/gh/xaoxuu/cdn-material-x@19.5/css/style.css
    js:
      # app: https://cdn.jsdelivr.net/gh/xaoxuu/cdn-material-x@19.5/js/app.js
      # search: https://cdn.jsdelivr.net/gh/xaoxuu/cdn-material-x@19.5/js/search.js
      # volantis: https://cdn.jsdelivr.net/gh/xaoxuu/volantis@1.0/js/volantis.min.js



############################### 主题风格 ###############################
# style: material    # material: 导航栏和标题栏背景是主题色
style: pure        # pure: 导航栏和标题栏背景是白色


############################### 服务开关 ###############################
scrollreveal: true
nodewaves: true
# busuanzi用于统计网页浏览次数，这个功能不能正常工作
busuanzi: flase
# fastclick: true



############################### 默认值 ###############################
# 音乐控件的默认配置，如果sidebar或者page里没有提供，就取这里的参数
music:
  enable: false      # 是否启用
  color: '#1BCDFC'  # 主题色
  mode: circulation # random （随机） single （单曲） circulation （列表循环） order （列表）
  server: netease   # netease（网易云音乐）tencent（QQ音乐） xiami（虾米） kugou（酷狗）
  type: playlist    # song （单曲） album （专辑） playlist （歌单） search （搜索）
  id: 2615636388    # 歌曲/专辑/歌单 ID
  volume: 0.7       # 音量, 0~1
  autoplay: false   # 自动播放

# 友链页头像占位图
avatar_placeholder: https://cdn.jsdelivr.net/gh/xaoxuu/assets@master/avatar/avatar.png

# 日期格式 http://momentjs.com/docs/
date_format: 'YYYY-MM-DD' # 文章发布日期的格式
# updated_date_format: 'll' # 文章更新日期的格式
updated_date_format: 'YYYY-MM-DD'

# 幻灯片
backstretch:
  position: full  # cover: 封面背景   full: 整个网页背景
  duration: 60000 # 持续时间（毫秒）
  fade: 25000     # 渐变（毫秒）
  images:
    - https://img.vim-cn.com/a3/7909fde90ed22e7a8d8e27883ba6650d45b234.jpg
    - https://img.vim-cn.com/29/793fd576933026ea4e21cdbe298b45fa15eb44.jpg
    - https://img.vim-cn.com/1e/7c48afe6c9733c82b31d7c1043e43e9a00bc85.jpg
    - https://img.vim-cn.com/74/c4f8924aba84f9ea2bbd1d2b397082c5ed8985.jpg



############################### 自定义 ###############################
# PC端主页封面
cover:
  scheme: search    # 后期将会提供多种封面方案
  height: half      # full（默认值）: 首页封面占据整个第一屏幕，其他页面占半个屏幕高度， half: 所有页面都封面都只占半个屏幕高度
  title: " "
  # logo: assets/logo.png    # logo和title只显示一个，若同时设置，则只显示logo
  # search_placeholder: '搜索'
  # 主页封面菜单
  features:
    - name: HOME
      icon: fas fa-home
      url: /
    - name: CS
      icon: fas fa-laptop-code
      url: categories/Computer-Science
    - name: MATH
      icon: fas fa-dice-d20
      url: categories/Mathematics
    - name: LIT
      icon: fas fa-book-reader
      url: categories/Literature
    # - name: 2
    #   icon: fas fa-link
    #   url: categories/Algorithm
    #   rel: nofollow
    # - name: 3
    #   icon: fas fa-info-circle
    #   url: categories/3
    #   rel: nofollow


# PC端顶部导航栏
menu_desktop:
  - name: CS
    icon: fas fa-laptop-code
    url: categories/Computer-Science
  - name: MATH
    icon: fas fa-dice-d20
    url: categories/Mathematics
  - name: LIT
    icon: fas fa-book-reader
    url: categories/Literature

# 移动端导航菜单（从右上角的按钮点击展开）
menu_mobile:
  # - name: RECENT
  #   icon: fas fa-clock
  #   url: /
  - name: CS
    icon: fas fa-laptop-code
    url: categories/Computer-Science
    rel: nofollow
  - name: MATH
    icon: fas fa-dice-d20
    url: categories/Mathematics
  - name: LIT
    icon: fas fa-book-reader
    url: categories/Literature
  - name: ARCHIVE
    icon: fas fa-archive
    url: archives/
    rel: nofollow
  - name: CATEGORIES
    icon: fas fa-folder-open
    url: categories/
    rel: nofollow
  - name: TAGS
    icon: fas fa-tags
    url: tags/
    rel: nofollow

# 默认的meta信息，文章中没有配置则按照这里的配置来显示，设置为false则不显示
# 其中，title只在header中有效，music和thumbnail无需在这里设置，文章中有则显示
# 如果tags放置在meta.header中，那么在post列表中不显示（因为卡片下方已经有了）
meta:
  # header: [title, author, date, categories, counter, top]
  # footer: [updated, tags, share]
  header: [title, date, updated, categories, tags]

# 主体元素，你也可以在页面的Front-matter中设置
# body: [article, comments]
body: [article]

# PC端侧边栏小部件，默认按下面给定的顺序全部显示，文章中还可以自定义显示一部分以及顺序
sidebar:
  - widget: author
    enable: false
    # avatar: https://cdn.jsdelivr.net/gh/xaoxuu/assets@master/avatar/avatar.png
    avatar: favicon.png
    social: true
  - widget: grid
    icon: fas fa-map-signs
    title: NAVIGATION
    rows:
      - name: 
        icon: fas fa-home
        url: /
      - name: 
        icon: fas fa-archive
        url: archives/
        rel: nofollow
      - name: 
        icon: fas fa-tags
        url: tags/
        rel: nofollow
      - name: 
        icon: fas fa-folder-open
        url: categories/
        rel: nofollow
  - widget: toc
  - widget: category
    enable: true
    more:
      icon: fas fa-expand-arrows-alt
      url: categories/
      rel: nofollow
  - widget: tagcloud
    icon: fas fa-fire
    more:
      icon: fas fa-expand-arrows-alt
      url: tags/
      rel: nofollow
  # - widget: related_posts # 需要安装插件  npm i -S hexo-related-popular-posts

############################### 杂项，请勿删除 ###############################
#valine配置
valine:
  enable: false # 如果你想用Valine评论系统，请设置enable为true
  volantis: true # 是否启用volantis版本（禁止匿名，增加若干贴吧、QQ表情）
  # 还需要在根目录配置文件中添加下面这三行内容
  # leancloud:
  #   app_id: 你的appId
  #   app_key: 你的appKey
  guest_info: nick,mail,link #valine comment header info
  placeholder: 快来评论吧~ # valine comment input placeholder(like: Please leave your footprints )
  avatar: mp # gravatar style https://valine.js.org/avatar
  pageSize: 10 # comment list page size
  verify: true # valine verify code (true/false)
  notify: true # valine mail notify (true/false)
  lang: zh-cn
  highlight: true

# 搜索配置
search:
  enable: true
  service: hexo
  # google
  google_api_key:
  google_engine_id:
  # algolia
  algolia_app_id:
  algolia_api_key:
  algolia_index_name:
  # azure
  azure_service_name:
  azure_index_name:
  azure_query_key:
  # baidu
  baidu_api_id:

# Less渲染
less:
  compress: true
